Repository micronaut-projects/micronaut-spring, pull requests merged in 2023-07, with the labels that each got.

#447 [spring] Update common files for branch master
  .github/workflows/graalvm-dev.yml
  .github/workflows/graalvm-latest.yml
  .github/workflows/gradle.yml
  .gitignore
Labels: relates-to: build

#455 Change docs to refer to `micronaut-platform`.
  src/main/docs/guide/micronautInsideSpring/springBootStarter.adoc
Labels: type: docs

#457 [spring] Update common files for branch master
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: relates-to: build

#463 Spring to Core 4.0.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#466 Spring no milestones
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#473 [spring] Update common files for branch master
  .github/workflows/graalvm-dev.yml
  .github/workflows/graalvm-latest.yml
  .github/workflows/gradle.yml
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build
